### ISSUE TITLE
Print map

### ISSUE THREAD

**Issue by redhog** [Programmeringskursen/roomgame#6]
Print a map of the rooms

**Comment by Murneh** [comment]
This is hard! I'm trying to make a method loop, sort of, while assigning local variables a starting value only once. I get about half the house mapped before it stops. Code is too broken to commit. Want a screenshot? Elin?

**Comment by redhog** [comment]
There is another type of loop that could be useful, in addition to for x in y:

   while something_is_true:
       something_else()

This will do something_else() until something_is_true becomes false.

**Comment by redhog** [comment]
Not sure this helps, you could also definitely upload a screenshot here :) Have you uploaded the broken code to github? Would be good to be able to look at what you're doing, and maybe Elin would have some insights too... It's usually easier for someone else to find out why ones code doesn't work than for yourself :P

**Comment by Murneh** [comment]
![screenshot from 2015-03-07 08 19 39](https://cloud.githubusercontent.com/assets/11146518/6540549/c570d1c8-c4a2-11e4-916e-163886fd80df.png)

I'm not working with actual loops here it seems. Maybe we should start over using for, or while.

**Comment by Murneh** [comment]
Print map has been solved!
